{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ecommerce-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "ecommerce.name" . }}
  policyTypes:
    - Ingress
  ingress:
    - {}
{{- end }}





