{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
{{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- /* Render storageClassName even when it's "" to avoid nil/empty mismatch for bound PVCs */ -}}
{{- if or (eq (toString .Values.persistence.storageClassName) "") (.Values.persistence.storageClassName) }}
  storageClassName: {{ default "" .Values.persistence.storageClassName | quote }}
{{- end }}
  volumeName: ecommerce-pv
{{- end }}

